# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 00:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('itemid', models.AutoField(db_column='ItemId', primary_key=True, serialize=False)),
                ('itemname', models.CharField(db_column='ItemName', max_length=100)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('price', models.IntegerField(db_column='Price')),
                ('category', models.CharField(choices=[('BOOKS', 'Books'), ('STATIONERY', 'Stationary'), ('ELECTRONICS', 'Electronics')], db_column='Category', max_length=25)),
                ('rating', models.IntegerField(blank=True, db_column='Rating', default=0, null=True)),
                ('numreviews', models.IntegerField(db_column='NumReviews', default=0)),
            ],
            options={
                'db_table': 'shop_item',
            },
        ),
    ]
